//TODO
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.Raid;

import Data.Cader;
import Data.Raid;
import InOut.FileHandler;
import java.text.ParseException;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dirk
 */
public class LoadRaidFrame extends javax.swing.JFrame {
    FileHandler preshowHandler;
    FileHandler fileHandler;
    RaidPanelAsParentInterface interFace;
    Raid raid;
    
    /**
     * Creates new form LoadRaidFrame
     */
    public LoadRaidFrame(Cader cader,RaidPanelAsParentInterface interFace) {
        this.interFace = interFace;
        this.preshowHandler = new FileHandler(new Cader());
        this.fileHandler = new FileHandler(cader);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dateList = new javax.swing.JList();
        cancelButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commentArea = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        dateSign = new javax.swing.JLabel();
        memberSign1 = new javax.swing.JLabel();
        lootSign = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        memberLabel1 = new javax.swing.JLabel();
        lootLabel = new javax.swing.JLabel();
        memberSign2 = new javax.swing.JLabel();
        memberLabel2 = new javax.swing.JLabel();

        dateList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        dateList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateListMouseClicked(evt);
            }
        });
        dateList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                dateListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(dateList);

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        loadButton.setText("laden");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Kommentar"));

        commentArea.setEditable(false);
        commentArea.setColumns(20);
        commentArea.setRows(5);
        jScrollPane1.setViewportView(commentArea);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dateSign.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateSign.setText("Datum:");

        memberSign1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberSign1.setText("Teilnehmer:");

        lootSign.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lootSign.setText("Loot:    ");

        dateLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dateLabel.setText("00-00-0000 00:00");

        memberLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberLabel1.setText("00/00");

        lootLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lootLabel.setText("0");

        memberSign2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberSign2.setText("Ersatz:");

        memberLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        memberLabel2.setText("00/00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dateSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(dateLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(memberSign1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memberLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lootSign)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lootLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(memberSign2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(memberLabel2)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateSign)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberLabel1)
                    .addComponent(memberSign1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memberSign2)
                    .addComponent(memberLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lootSign)
                    .addComponent(lootLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(loadButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton))
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
        interFace.drawAll();
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        JFrame frame = new JFrame("ChangeDialog");
        int n = JOptionPane.showConfirmDialog(
            frame,
            "Bisherigen Änderungen werden gelöscht!\n Wirklich fortfahren?",
            "Raid Laden",
            JOptionPane.YES_NO_OPTION);
        if(n==0){
            interFace.setRaid(fileHandler.readRaid(raid.getTimestamp()));
            setVisible(false);
            interFace.drawAll();
            dispose();
        }
    }//GEN-LAST:event_loadButtonActionPerformed

    private void dateListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_dateListValueChanged

    }//GEN-LAST:event_dateListValueChanged

    private void dateListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateListMouseClicked
            getRaid();
    }//GEN-LAST:event_dateListMouseClicked

    
    public void open(){
        LinkedList<Date> dates = preshowHandler.getRaidDates();
        String[] listData = new String[dates.size()];
        
        for(int i=0;i<dates.size();i++){
            listData[i] = Cader.showDateFormat.format(dates.get(i));
        }
        if(dateList.getFirstVisibleIndex()>=0){
            dateList.setListData(listData);
            dateList.setSelectedIndex(0);
            getRaid();
        }
        
        setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextArea commentArea;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JList dateList;
    private javax.swing.JLabel dateSign;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton loadButton;
    private javax.swing.JLabel lootLabel;
    private javax.swing.JLabel lootSign;
    private javax.swing.JLabel memberLabel1;
    private javax.swing.JLabel memberLabel2;
    private javax.swing.JLabel memberSign1;
    private javax.swing.JLabel memberSign2;
    // End of variables declaration//GEN-END:variables

    private void getRaid(){
        try {
            String str = (String)dateList.getSelectedValue();
            Date date = Cader.showDateFormat.parse(str);
            this.raid =preshowHandler.readRaid(date);
            drawPreShow();
        } catch (ParseException ex) {
        }
    }
    
    
    private void drawPreShow(){
        String line=Cader.showDateFormat.format(raid.getTimestamp());
        dateLabel.setText(line);
        String[] names = raid.getMembersNames();
        int countTLG=0;
        int countERS=0;
        for(int i=0;i<names.length;i++){
            switch(raid.getMemberByName(names[i]).getState()){
                    case TEILG: 
                        countTLG++;
                        break;
                    case ERSATZ:
                        countERS++;
                        break;
            }
        }
        memberLabel1.setText(countTLG+"//"+names.length);
        memberLabel2.setText(countERS+"//"+names.length);
        lootLabel.setText(""+raid.getlootDates().length);
    }
}
