/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui.Raid;

import Data.Member;
import Data.Raid;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dirk
 */
public class SKSFrame extends javax.swing.JFrame {

    /**
     * Creates new form SKSFrame
     */
    public SKSFrame(Raid raid) {
        initComponents();
        LinkedList<Member> members = raid.getFullSKS();
        
        Object[] newRow;
        DefaultTableModel raidModel = (DefaultTableModel)memberTable.getModel();
        for (int i=0;i<members.size();i++){
            Member member = members.get(i);
            newRow = new Object[5];
            newRow[0]= i+1;
            newRow[1]= member.getPlayer().getName();
            newRow[2]= member.getPlayer().getStringRole();
            newRow[3]= member.getPlayer().getStringMainSpec();
            newRow[4]= member.getPlayer().getStringSecondSpec();
            raidModel.addRow(newRow);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        memberTable = new javax.swing.JTable();

        memberTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Name", "Klasse", "Main Rolle", "Second Rolle"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        memberTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(memberTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable memberTable;
    // End of variables declaration//GEN-END:variables
}
